version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Check code format
          command: diff -u <(echo -n) <(gofmt -d ./)
      - run:
          name: Build (Linux 64Bits)
          command: |
            GOOS=linux GOARCH=amd64 make EXE_NAME=email-cli_linux
      - run:
          name: Build (FreeBSD 64Bits)
          command: |
            GOOS=freebsd GOARCH=amd64 make EXE_NAME=email-cli_freebsd
      - run:
          name: Test
          command: make test
      - run:
          name: Build (Mac 64Bits)
          command: |
            GOOS=darwin GOARCH=amd64 make EXE_NAME=email-cli_darwin
      - run:
          name: Build (Windows 64Bits)
          command: |
            GOOS=windows GOARCH=amd64 make EXE_NAME=email-cli_win.exe
      - run:
          name: "Publish Release on GitHub"
          command: |
            mkdir pkg bin && cp -aR email* pkg/
            curl -skLO https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
            tar -xf upx-3.96-amd64_linux.tar.xz
            cp upx-3.96-amd64_linux/upx bin/
            rm -rf upx-3.96-amd64_linux upx-3.96-amd64_linux.tar.xz
            bin/upx pkg/email-cli_win.exe pkg/email-cli_darwin pkg/email-cli_linux
            go get -u github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${TAG_VERSION} ./pkg/
            

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
