version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Check code format
          command: diff -u <(echo -n) <(gofmt -d ./)
      - run:
          name: Build (linux)
          command: |
            make build EXE_NAME=email_linux_amd64
            pwd
            ls -ila
      - run:
          name: Test
          command: make test
      - run:
          name: Build (mac)
          command: |
            make build_mac EXE_NAME=email_darwin_amd64
      - run:
          name: Build (win)
          command: |
            make build_win EXE_NAME=email_win_amd64.exe
      - store_artifacts:
          path: ~/email_linux_amd64
          destination: bin/email_linux_amd64
      - store_artifacts:
          path: ~/email_darwin_amd64
          destination: bin/email_darwin_amd64


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
