version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Check code format
          command: diff -u <(echo -n) <(gofmt -d ./)
      - run:
          name: Build (linux)
          command: |
            make build
      - run:
          name: Test
          command: make test
      - run:
          name: Build (mac)
          command: |
            make build_mac
      - run:
          name: Build (win)
          command: |
            make build_win
      - store_artifacts:
          path: ~/project/email_linux_amd64
          destination: bin/email_linux_amd64
      - store_artifacts:
          path: ~/project/email_darwin_amd64
          destination: bin/email_darwin_amd64
      - store_artifacts:
          path: ~/project/email_win_amd64
          destination: bin/email_win_amd64

  publish:
    docker:
      - image: circleci/golang:1.14
    steps:
      - attach_workspace:
          at: ./bin/
      - run:
          name: "Publish Release on GitHub"
          command: |
            ls -ila
            go get github.com/tcnksm/ghr
            VERSION=$(bin/email_linux_amd64 --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - publish
