version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Check code format
          command: diff -u <(echo -n) <(gofmt -d ./)
      - run:
          name: Build (linux)
          command: |
            make build
      - run:
          name: Test
          command: make test
      - run:
          name: Build (mac)
          command: |
            make build_mac
      - run:
          name: Build (win)
          command: |
            make build_win
      - run:
          name: "Publish Release on GitHub"
          command: |
            mkdir pkg && cp -aR *amd* pkg/     
            go get -u github.com/tcnksm/ghr
            ls pkg/
            VERSION=$(./pkg/email_linux_amd64 --version)
            CMD="-u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1}"
            ghr ${CMD} v0.1.0 pkg/
            

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
