version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Check code format
          command: diff -u <(echo -n) <(gofmt -d ./)
      - run:
          name: Build (linux)
          command: |
            make build
      - run:
          name: Test
          command: make test
      - run:
          name: Build (mac)
          command: |
            make build_mac
      - run:
          name: Build (win)
          command: |
            make build_win
      - run:
          name: "Publish Release on GitHub"
          command: |
            echo 'export VERY_V=$(./email_linux_amd64 --version)' >> $BASH_ENV
            source $BASH_ENV
            TAG="echo ${VERY_V}"
            mkdir pkg bin && cp -aR *amd* pkg/
            curl -skLO https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
            tar -xf upx-3.96-amd64_linux.tar.xz
            cp upx-3.96-amd64_linux/upx bin/
            rm -rf upx-3.96-amd64_linux upx-3.96-amd64_linux.tar.xz
            bin/upx pkg/email_linux_amd64
            bin/upx pkg/email_win_amd64.exe
            bin/upx pkg/email_darwin_amd64
            go get -u github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${TAG} ./pkg/
            

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
